version: '3.9'
services:
  db:
    environment: 
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
      PGDATA: "/var/lib/postgresql/data"
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 14332:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: