version: '3.9'
services:
  api:
    build:
      context: ./ExpenseTracker
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
  db:
    environment: 
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_DB: "${DB_NAME}"
      PGDATA: "/var/lib/postgresql/data"
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 14332:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: